name                  = "cosmic-picnic"
compatibility_date    = "2025-10-01"
compatibility_flags   = ["nodejs_compat"]
pages_build_output_dir = "website/out"

[assets]
directory = "./website/out"

[[d1_databases]]
binding       = "DB"
database_name = "cosmic-picnic-signups"
database_id   = "646e91df-cae4-4e61-bb46-bf292797c062"
